repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: import-linter
        name: import-linter
        entry: "lint-imports --config=ticket-search-workflow/.importlinter"
        language: python
        types: [python]
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-ll"]
        files: .py$

  - repo: local
    # We do not use pre-commit/mirrors-mypy,
    # as it comes with opinionated defaults
    # (like --ignore-missing-imports)
    # and is difficult to configure to run
    # with the dependencies correctly installed.
    hooks:
      - id: mypy
        name: mypy
        entry: "mypy"
        files: .py$
        language: python
        # use your preferred Python version
        language_version: python3.10
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # Print the number of files as a sanity-check
        verbose: true
